### ISSUE TITLE
Document `atLevel` and `setLevel` rename

### ISSUE THREAD

**Issue by ulope** [eisensheng/pytest-catchlog#12]
It seems that during the fork the `atLevel` and `setLevel` methods of the `caplog` fixture have been de-camelized to `at_level` and `set_level`. This however is not mentioned in the README.

**Comment by abusalimov** [comment]
Thanks for reporting this!

We actually have PR #11 addressing backward compatibility issues, it should be merged soon, I hope.

Probably one of the next steps could be to list all differences between the fork and the original plugin. FWIW, there is #4 for that.

**Comment by The-Compiler** [comment]
I think this can be closed as there's #4?

**Comment by eisensheng** [comment]
Maybe. I forgot to actually document that `atLevel` and `setLevel` are going through a deprecation phase. This should be noted though. I guess this will go in a Patch release before I close the issue.

**Comment by eisensheng** [comment]
1.2.1 has been released with a warning regarding the `atLevel` and `setLevel` methods.
