### ISSUE TITLE
Rename plugin to pytest-logging

### ISSUE THREAD

**Issue by eisensheng** [eisensheng/pytest-catchlog#19]
Rename the Plugin to pytest-logging.

The main argument against the rename was that a third name may further stir the confusion around the logging plugins for pytest.

This argument is somewhat obsolete now since a new plugin with the name pytest-logging actually appeared and further stirred the confusion around the logging plugins. So the plugin pytest-catchlog should be renamed to pytest-logging once the functionality of the current pytest-logging plugin has been merged into pytest-catchlog.

I still want a dream catcher for the logo of this plugin though!

**Comment by s0undt3ch** [comment]
#20 should prepare catchlog for this

**Comment by s0undt3ch** [comment]
Let me know when you want to take care of this. I recently had 2 users trying to install pytest-logging which I directed to pytest-catchlog.

**Comment by abusalimov** [comment]
Sure!

**Comment by nicoddemus** [comment]
How is the status of this? IIUC, once this is renamed to `pytest-logging` we would like move it to the `pytest-dev` organization, correct?

pytest-dev/pytest#2159 has brought me back to this issue. 😁

**Comment by s0undt3ch** [comment]
Just tell me when and I'll pull the plug on the old pytest-logging plugin.

**Comment by nicoddemus** [comment]
Gentle ping to know about the status. 😁 

cc @The-Compiler

**Comment by The-Compiler** [comment]
No idea, I tuned out of here. This is probably something @eisensheng would need to do, as he's the owner of the package on PyPI and the repo and all that.

**Comment by twmr** [comment]
What if  we do the renaming and the merge (#8) into pytest-dev in one go? Then we would no
longer have to wait for the feedback from @eisensheng.

**Comment by nicoddemus** [comment]
@thisch why would doing both at the same time give us the right to do it without the author's knowledge?

**Comment by nicoddemus** [comment]
Hmm it's worrying that the last activity on GitHub by @eisensheng was in September 2016, according to his profile... It would be nice if he could give us a ping here.

**Comment by nicoddemus** [comment]
@thisch oh just realized you meant merging with pytest-logging, and not merging it with the pytest-dev organization, sorry for the confusion com my part. I see your point now.

**Comment by twmr** [comment]
I didn't know that there is a pytest-logging package on pypi (Now I understand what @s0undt3ch meant in https://github.com/eisensheng/pytest-catchlog/issues/19#issuecomment-269308977). I really meant merging pytest-catchlog into pytest-dev/pytest, as requested in #8. I would also prefer if @eisensheng gives us a +1, but what if he doesn't respond?

**Comment by nicoddemus** [comment]
Yeah we have to decide what to do, @eisensheng has been inactive from GitHub for a year now. ☹️

**Comment by nicoddemus** [comment]
@s0undt3ch are you still interested on the merge of pytest-catchlog + pytest-logging and the move to pytest-dev? And if so would you be the main maintainer over pytest-dev/pytest-logging?

**Comment by s0undt3ch** [comment]
Yep, I haven't developed my plugin further just to get them both merged. As to taking principal role in managing the project, I also don't have much free time these days, ideally, someone with some more available time should take up that role.

**Comment by s0undt3ch** [comment]
Also, if pytest is open to include this functionality into core of pytest, I'd vote for that.

**Comment by twmr** [comment]
I volunteer to integrate this plugin into pytest-dev.

**Comment by s0undt3ch** [comment]
@thisch feel free to CC me on your PR or ping me if you need any help.
I'd like to take your code for a spin to see if what was included from pytest-logging is still working :)
But I'm sure you'll do awesome work!

Thanks for stepping up.

**Comment by twmr** [comment]
You can already take a look at my feature branch [here](https://github.com/thisch/pytest/tree/catchlog). Before I create a pull request on pytest-dev, I would first like to wait a bit until I get a few more comments from other developers. My feature branch does not yet include any code from pytest-logging. What exactly do you need from your plugin?

**Comment by twmr** [comment]
@s0undt3ch have you tested my feature branch yet?

If you are satisfied, I'll create a PR, provided that no one objects.

**Comment by s0undt3ch** [comment]
Sorry @thisch, I have not. I'm on vacations. I'll see if I can give it a spin on Monday morning.

**Comment by twmr** [comment]
Never mind. I'll create a PR for pytest-dev/pytest tomorrow, if no one objects.

**Comment by abusalimov** [comment]
~Just in case, @eisensheng has added me and @The-Compiler as the repository owner, so when the time comes IIUC we should be able to move the repository to the pytest-dev org so that all the issues and PR of this repository are retained. I'm not sure about PyPI and Travis accounts though.~

Oops, disregard the above. Turns out, we only have push access, and can't manage the GitHub repository.

**Comment by The-Compiler** [comment]
Since the pytest-catchlog plugin was merged into the pytest core, this probably isn't applicable anymore.
