### ISSUE TITLE
Captured log is printed twice if there's an error in the test and during teardown

### ISSUE THREAD

**Issue by The-Compiler** [eisensheng/pytest-catchlog#29]
When there's a situation where we have an error in a test _and_ during teardown:

``` python
import logging
import pytest

@pytest.yield_fixture
def fixt():
    yield
    raise Exception


def test_foo(fixt):
    logging.debug("Hello World")
    raise ValueError
```

Then the log is printed twice:

```
=========================== ERRORS ===========================
_______________ ERROR at teardown of test_foo ________________

    [...]

logtest.py:7: Exception
--------------------- Captured log call ----------------------
logtest.py                  11 DEBUG    Hello World
========================== FAILURES ==========================
__________________________ test_foo __________________________

    [...]

logtest.py:12: ValueError
--------------------- Captured log call ----------------------
logtest.py                  11 DEBUG    Hello World
```

Some background:

This happens quite often for me, as I start a subprocess in a test and parse its output. When there's an unparsable line, I want to fail the test but continue so I get more output (imagine e.g. a traceback - I don't want to abort the test on the first unparsable line as there's more useful information to come). So what I do is to set a flag, and raise an error during teardown (in a fixture) when there's an unparseable line.

Now if there is something like that, chances are the test itself will also have failed in some way, and I get the whole debug log (often dozens to hundreds of lines) twice.

**Comment by abusalimov** [comment]
Isn't this a pytest core issue? Using `print` in place of `logging.debug` gives the same effect:

```
==================================== ERRORS ====================================
________________________ ERROR at teardown of test_foo _________________________
tests/test_xxx.py:7: in fixt
    raise Exception
E   Exception
----------------------------- Captured stdout call -----------------------------
Hello World
=================================== FAILURES ===================================
___________________________________ test_foo ___________________________________
tests/test_xxx.py:12: in test_foo
    raise ValueError
E   ValueError
----------------------------- Captured stdout call -----------------------------
Hello World
```

**Comment by The-Compiler** [comment]
Hmm, interesting, I guess it is indeed. I'll report it there then.

**Comment by The-Compiler** [comment]
I added it to https://github.com/pytest-dev/pytest/issues/1004
