### ISSUE TITLE
__multicall__ being deprecated in upcoming pytest release

### ISSUE THREAD

**Issue by The-Compiler** [eisensheng/pytest-catchlog#3]
When using pytest-catchlog with pytest from [their git repo](https://github.com/pytest-dev/pytest) and `-rw` (show warnings), I get:

```
.../pytest_catchlog.py:71 'pytest_runtest_makereport' hook uses deprecated __multicall__ argument
```

**Comment by The-Compiler** [comment]
I'm thinking about fixing this separately from #7 as I really want to switch to pytest 2.8 without getting warnings :wink:

@eisensheng Would you do a new release for me if I fixed this?
@abusalimov Is it okay if I introduce merge conflicts in your PR (sorry!)?

**Comment by abusalimov** [comment]
@The-Compiler Sorry for delaying this show stopper.

I've stripped out any API-breaking changes from the PR recently, but have not pushed yet because of few failing tests.
I arrived to Prague yesterday and now I have better Internet here and a bit more quite time. I'm going to fix remaining tests and force-push #7 this evening so that you could review the corresponding `__multicall__` fix.

Is it OK for you?

**Comment by The-Compiler** [comment]
Ah, awesome! Sounds good to me.

Probably makes sense to move the API/LineMatcher changes to a separate PR anyways as they might take a little bit more time/discussion.

Thanks for all your work on catchlog, I really appreciate it!

**Comment by eisensheng** [comment]
> I've stripped out any API-breaking changes from the PR recently, but have not pushed yet because of few failing tests.

Too bad. I was all in favour for the API break. We could simply release 1.2 with the feature to pull configuration from the cfg file and a fix for `__multicall__` and introduce the API break with a 2.0 version.

This would also be the safest upgrade path for current users of the original plugin and this fork. (If there are any users of this fork that is …)

**Comment by abusalimov** [comment]
That doesn't mean that I've thrown all that changes into to a trashcan :recycle:
I was going to suggest them in a separate PR, just not to block #7 for too long.
