### ISSUE TITLE
Introduce flake8 to ensure code styling consistency

### ISSUE THREAD

**Issue by eisensheng** [eisensheng/pytest-catchlog#48]
I would like to start a discussion on introducing Flake8 to check and ensure code styling consistency. 

The styling check should also be introduced into the `tox.ini` file to guarantee that styling mistakes are detected during test runs with travis. The goal is to ensure that code will be written in a consistent manner and confusion on styling for code contributions will be reduced.

Subjects I would like to discuss here are:
- Whenever it actually makes sense to enable flake8 now.
- Having travis to mark a build as failed whenever flake8 complained about something.
- Which plugins to use. (`flake8-docstrings`, `flake8-import-order`, `flake8-print`, … )
- Which warnings to enable and to disable.

**Comment by The-Compiler** [comment]
Sounds good to me, I think consistency is always a good idea.

Depending how far you want to go, some other linters might also be a good idea: I can highly recommend [pylint](http://www.pylint.org/) - even if it needs some configuration, after that it's really powerful. Then there also are [check-manifest](https://pypi.python.org/pypi/check-manifest) (MANIFEST.in), [pyroma](https://pypi.python.org/pypi/pyroma) (setup.py) and [vulture](https://pypi.python.org/pypi/vulture) (unused code - probably not useful in a project in this small scale) as more specialised linters.

As for flake8 plugins, FWIW here's what I use: https://github.com/The-Compiler/qutebrowser/blob/master/misc/requirements/requirements-flake8.txt-raw

**Comment by The-Compiler** [comment]
Since this was fixed in `development`, and the pytest-catchlog plugin (the `development` branch) was merged into the pytest core, this probably isn't applicable anymore.
