### ISSUE TITLE
live logging settings not always visible in pytest helptext

### ISSUE THREAD

**Issue by twmr** [eisensheng/pytest-catchlog#51]
Inside the pytest-catchlog working directory I see the following catchlog-specific cmd line settings:

```
Log catching:
  --no-print-logs       disable printing caught logs on failed tests.
  --log-level=LOG_LEVEL
                        logging level used by the logging module
  --log-format=LOG_FORMAT
                        log format as used by the logging module.
  --log-date-format=LOG_DATE_FORMAT
                        log date format as used by the logging module.
  --log-cli-level=LOG_CLI_LEVEL
                        cli logging level.
  --log-cli-format=LOG_CLI_FORMAT
                        log format as used by the logging module.
  --log-cli-date-format=LOG_CLI_DATE_FORMAT
                        log date format as used by the logging module.
```

However, if `pytest --help` is run from a different directory, not all of these settings are available

```
Log catching:
  --no-print-logs       disable printing caught logs on failed tests.
  --log-format=LOG_FORMAT
                        log format as used by the logging module.
  --log-date-format=LOG_DATE_FORMAT
                        log date format as used by the logging module.

```

Any ideas why the help text is different?  (tested on python3.5; pytest-3.0.0)

**Comment by twmr** [comment]
I nailed it down to a pip issue. (I was not able to reproduce this issue in a fresh conda environment).

**Comment by smallnamespace** [comment]
Can you re-open, or should I file a another issue? I'm running into the same problem.

In particular, I see this in a freshly installed conda env with py3.6, pip, and pytest only, and I'm unable to see the `cli` options even running from the site-packages dir.
