### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by arnuschky** [eisensheng/pytest-catchlog#66]
We're heavily depending on colors to structure our logs visually. Any chance to get catchlog to maintain them? Currently, the output shows only in monochrome.

**Comment by twmr** [comment]
We use a custom [formatter](https://docs.python.org/2/library/logging.html#formatter-objects) for this, but it is not currently possible to specify this formatter on the cmd line for pytest AFAIK.

**Comment by arnuschky** [comment]
I realized that it works quite alright with colors - at least when catching stderr/stdout. I lost the colors in a different pay (secondary process via popen).

I am closing this, works for me.

**Comment by gsemet** [comment]
+1 on allowing color in output terminal. Even a simpler one using colorlog formatter would be fine (and optional, only enabled if colorlog module is available)
Thanks
