### ISSUE TITLE
Cannot setup `log_format` in `setup.cfg, because of `InterpolationMissingOptionError`

### ISSUE THREAD

**Issue by prokher** [eisensheng/pytest-catchlog#67]
I would like to setup `log_format` in the project-wise configuration file `setup.cfg`. I do it like this:
```
[tool:pytest]
log_format = %(filename)s:%(lineno)d %(name)s%(levelname)s%(message)s
```

Given this, any invocation of some `setup.py` or simply `pip install -r requirements.txt` in the directory where `setup.cfg` resides, gives me a error:
```
configparser.InterpolationMissingOptionError: Bad value substitution: option 'log_format' in section 'tool:pytest' contains an interpolation key 'filename' which is not a valid option name. Raw value: '%(filename)s:%(lineno)d %(name)s%(levelname)s%(message)s'
```

As far as I understand, the reason is that %-formatting is used in config files for string interpolation. It is recommended to screen `%` with another `%` to avoid interpolation. Well, if I do this then `pytest-catchlog` stops interpreting this string as format and simply output it as is.

It looks like, `pytest-catchlog` shall adopt the rules of writing `setup.cfg` files. If there is another solution or workaround, please let me know.

**Comment by twmr** [comment]
I can reproduce this. I'll try to come up with a fix for this

**Comment by twmr** [comment]
The reason why pytest does not raise this ``InterpolationMissingOptionError`` exception is that pytest (or py) does not use the ``configparser`` stdlib but a custom one, which does not depend on the ``configparser`` module (``py.iniconfig.IniConfig`` - > https://github.com/pytest-dev/py/blob/master/py/_vendored_packages/iniconfig.py). IMO pytest/py should also raise this ``InterpolationMissingOptionError`` exception.

**Comment by twmr** [comment]
Escaping % in setup.cfg does not work in python 2.x (see https://www.mail-archive.com/distutils-sig@python.org/msg26612.html and https://bugs.python.org/issue20754l)

**Comment by prokher** [comment]
Since this plugin merged to PyTest itself, the report moved to PyTest tracker [here](https://github.com/pytest-dev/pytest/issues/3062).
