### ISSUE TITLE
caplog.clear() does not works

### ISSUE THREAD

**Issue by rudicba** [eisensheng/pytest-catchlog#71]
AttributeError: 'CompatLogCaptureFixture' object has no attribute 'clear'

`pip freeze | grep pytest

pytest==3.2.1
pytest-catchlog==1.2.2
pytest-mock==1.6.2
`

**Comment by rudicba** [comment]
My bad

`pip freeze | grep pytest

pytest==3.2.1
-e git+https://github.com/eisensheng/pytest-catchlog.git@8eb1226c2f97d7eaca14762d88ce53fa07962ab8#egg=pytest_catchlog
pytest-mock==1.6.2`

Works as expected.

So when will be available the new version?

Thanks

**Comment by twmr** [comment]
We'll try to merge pytest-catchlog into pytest-core (see #8). Can you please close this issue?
