### ISSUE TITLE
Can we get a release of this?

### ISSUE THREAD

**Issue by gtmanfred** [eisensheng/pytest-catchlog#72]
There are some change we are using in https://github.com/saltstack/salt.git, and would like to just be able to install from the pypi package.

Thanks!
Daniel

**Comment by twmr** [comment]
You mean a release for the current state of the develop branch?

This plugin (develop branch) will soon be part of pytest see https://github.com/pytest-dev/pytest/pull/2794

**Comment by gtmanfred** [comment]
Ahh, ok awesome.

Thanks!
