### ISSUE TITLE
conflicts with pytest-capturelog

### ISSUE THREAD

**Issue by tmc** [eisensheng/pytest-catchlog#75]
As referenced in https://github.com/freedomofpress/securedrop/issues/2773 it appears as though this package and pytest-capturelog cannot both be installed -- is this something that would be considered in-scope for this project?

It would make for a bit of a rough transition otherwise.

**Comment by The-Compiler** [comment]
I don't know whether that's even possible, as it's quite early in the initialization phase where the conflict happens. Also note that this plugin is deprecated anyways, as the functionality got merged into the pytest core.

**Comment by tmc** [comment]
Thanks. It's not immediately apparent from the repo that it has been upstreamed -- perhaps this repo should be updated to point folks in the right direction.
